# __________________VARIABLES DE DELEGACIONES____________________
MIN_MORAL_DELEGACIONES = 0
MAX_MORAL_DELEGACIONES = 100
MENOR_MORAL_PARA_FICHAR = 20
COSTO_ENTRENAR_DEPORTISTA = 30
COSTO_SANAR_DEPORTISTA = 30
COSTO_TECNOLOGIA = 20
COSTO_HABILIDAD_ESPECIAL = 20
AUMENTO_EFECTIVIDAD_IMPLEMENTOS = 1.1
# FORMULA SANAR
INFERIOR_MIN = 1
INFERIOR_MAX = 0
DIVISOR = 200
# VARIABLES IEEESPARTA
EFECTIVIDAD_ENTRENAMIENTO_IEEE = 1.7
MIN_EXELECIA_RESPETO_IEE = 0.4
MAX_EXELECIA_RESPETO_IEE = 0.8
MIN_IMP_DEPORTIVOS_IEE = 0.3
MAX_IMP_DEPORTIVOS_IEE = 0.7
MIN_IMP_MEDICOS_IEE = 0.2
MAX_IMP_MEDICOS_IEE = 0.6
# VARIABLES DCCROTONA
MIN_EXELECIA_RESPETO_DCC = 0.3
MAX_EXELECIA_RESPETO_DCC = 0.7
MIN_IMP_DEPORTIVOS_DCC = 0.2
MAX_IMP_DEPORTIVOS_DCC = 0.6
MIN_IMP_MEDICOS_DCC = 0.4
MAX_IMP_MEDICOS_DCC = 0.8
EFECTIVIDAD_ENTRENAMIENTO_DCC = 1

# __________________VARIABLES DE DEPORTISTAS_____________________
# VELOCIDAD (PROPERTIES)
MIN_VELOCIDAD_DEPORTISTAS = 0
MAX_VELOCIDAD_DEPORTISTAS = 100
# RESISTENCIA (PROPERTIES)
MIN_RESISTENCIA_DEPORTISTAS = 0
MAX_RESISTENCIA_DEPORTISTAS = 100
# FLEXIBILIDAD (PROPERTIES)
MIN_FLEXIBILIDAD_DEPORTISTAS = 0
MAX_FLEXIBILIDAD_DEPORTISTAS = 100
# MORAL (PROPERTIES)
MIN_MORAL_DEPORTISTAS = 0
MAX_MORAL_DEPORTISTAS = 100
# METODO ENTRENAR
AUMENTO_MORAL_POR_ENTRENAMIENTO = 1  # Delegacion, pero al jugador
PUNTOS_ENTRENAMIENTO = 2

# __________________VARIABLES DE DEPORTES_____________________
# RIESGOS DEPORTES
RIESGO_LEISON_ATLETISMO = 0.2
RIESGO_LESION_CICLISMO = 0.35
RIESGO_LESION_GIMNASIA = 0.3
RIESGO_LESION_NATACION = 0.25
# PONERADORES CALCULAR GANADOR POR DEPORTE
# ____ VELOCIDAD _____
PONDERADOR_VELOCIDAD_ATLETISMO = 0.55
PONDERADOR_VELOCIDAD_CICLISMO = 0.47
PONDERADOR_VELOCIDAD_NATACION = 0.45
# ____ RESISTENCIA _____
PONDERADOR_RESISTENCIA_ATLETISMO = 0.2
PONDERADOR_RESISTENCIA_CICLISMO = 0.36
PONDERADOR_RESISTENCIA_GIMNASIA = 0.3
PONDERADOR_RESISTENCIA_NATACION = 0.3
# ____ FLEXIBILIDAD _____
PONDERADOR_FLEXIBILIDAD_CICLISMO = 0.17
PONDERADOR_FLEXIBILIDAD_GIMNASIA = 0.5
PONDERADOR_FLEXIBILIDAD_NATACION = 0.25
# ____ MORAL _____
PONDERADOR_MORAL_ATLETISMO = 0.25
PONDERADOR_MORAL_GIMNASIA = 0.2
# VARIABLES DEPORTES
PUNTAJE_MINIMO = 0
NIVEL_IMPLEMENTOS = 0

# __________________VARIABLES DE CAMPEONATO___________________
# DIA INICIAL Y DURACION
DIAS_COMPETENCIA = 6
DIA_INICIAL_COMPETENCIA = 0
# PREMIACION
PREMIO_MORAL_GANADOR = 20
BAJA_MORAL_PERDEDOR = 10
PREMIO_EXE_RESP_GANADOR = 0.1
BAJA_EXE_RESP_PERDEDOR = 0.02
DINERO_GANADOR = 100
