from PyQt5.QtCore import Qt

PASO_PRINCIPIANTE = 1000
PASO_AFICIONADO = 750
PASO_MAESTRO = 500

ALTO_FLECHA = 30

VELOCIDAD_FLECHA = 2
RAPIDEZ_FLECHA_DORADA = 1.5

PROB_FLECHA_NORMAL = 0.5
PROB_FLECHA_X2 = 0.7
PROB_FLECHA_DORADA = 0.95
PROB_FLECHA_HIELO = 1

LEFT_ARROW = Qt.Key_A
UP_ARROW = Qt.Key_W
DOWN_ARROW = Qt.Key_S
RIGHT_ARROW = Qt.Key_D
STOP_KEY = Qt.Key_P

LETRA_M = Qt.Key_M
LETRA_O = Qt.Key_O
LETRA_N = Qt.Key_N
LETRA_I = Qt.Key_I
LETRA_V = Qt.Key_V

PONDERADOR_X2 = 2
PONDERADOR_DORADA = 10
PONDERADOR_HIELO = 0.2

DURACION_CANCION_PRINCIPIANTE = 30
DURACION_CANCION_AFICIONADO = 45
DURACION_CANCION_MAESTRO = 60

APROBACION_PRINCIPIANTE = 30
APROBACION_AFICIONADO = 50
APROBACION_MAESTRO = 70

PUNTOS_FLECHA = 1

APROBACION_FORMULA = 100

COMBO_INICIAL = 0
AUMENTO_COMBO = 1
RESETEO_COMBO = 0

DINERO_INICIAL = 7000
VALUE_PINGUIRIN = 7000

DINERO_TRAMPA = 2500
